### get similarity of two sentences
POST http://127.0.0.1:8000/predict HTTP/1.1
content-type: application/json

{
    "image_id": 1,
    "leaderboard_name": "Harry",
    "actual_description": "That is a happy person",
    "guess_description": "That is a happy dog"
}