from typing import Tuple

from PIL import Image
import pandas as pd
import gradio as gr

from . import api_calls

LEADERBOARD_K = 10

def get_new_sample() -> Tuple[int, Image.Image, str, str, str, float, pd.DataFrame]:
	image_id, description, image = api_calls.get_image()
	leaderboard = api_calls.get_leaderboard(image_id, k=LEADERBOARD_K)
	return image_id, image, description, None, None, None, leaderboard

def get_similarity(image_id: int, actual_description: str, guess_description:str,
	leaderboard_name:str = "John Dough"
) -> Tuple[float, pd.DataFrame]:
	similarity = api_calls.calculate_similarity_score(image_id, actual_description, guess_description, leaderboard_name)
	leaderboard = api_calls.get_leaderboard(image_id, k=LEADERBOARD_K)
	return similarity, leaderboard

def get_frontend() -> gr.Blocks:
	initial_id, initial_image, initial_description, _, _, _, initial_leaderboard = get_new_sample()
	with gr.Blocks() as demo:
		with gr.Row():
			introduction = gr.Markdown("""
				# Reverse pictionary

				An AI generated picture is presented to you on the left hand 
				side. Your task is to guess, which query was used to generate that 
				image. Your submission will be scored against the true image and
				the query similarity, as measured by another AI model is returned.

				The pictures were generated by either DALL-E or by the Stable 
				Diffusion model. The text similarity is measured a sentence 
				transformer model from the Huggingface hub "sentence-transformers/all-MiniLM-L6-v2"
			""")
		with gr.Row():
			with gr.Column(scale=1):
				candidate_image = gr.Image(initial_image ,type="pil", shape=(20,20))
			with gr.Column(scale=1):
				leaderboard = gr.Dataframe(value=initial_leaderboard, row_count=(10,'fixed'), max_rows=10)
			with gr.Column(scale=1):
				id = gr.Textbox(value=initial_id, label="Id", visible=False)
				actual_description = gr.Textbox(value=initial_description, label="Actual description", visible=False)
				leaderboard_name = gr.Textbox(label="Name on Leaderboard", placeholder="John Dough")
				description_guess = gr.Textbox(label="Image description guess", lines=2)
				similarity_score = gr.Number(label="Similarity score")
				submit = gr.Button("Submit")
				submit.click(
					fn=get_similarity,
					inputs=[id, actual_description, description_guess, leaderboard_name],
					outputs=[similarity_score, leaderboard]
				)
				new_image = gr.Button("Get new image")
				new_image.click(
					fn=get_new_sample,
					inputs=None,
					outputs=[id, candidate_image, actual_description, description_guess, leaderboard_name, similarity_score, leaderboard]
				)
	demo.launch()
	return demo

if __name__ == "__main__":
	frontend = get_frontend()
